spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/chats
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
            database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true
  liquibase:
    change-log: classpath:db/prod/db-initdata.xml
  servlet:
    multipart:
      max-file-size: 10MB
security:
  jwt:
    # validity time in minutes
    validity-time: 30
---
spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:mem:homework;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:db/dev/db-initdata.xml
security:
  jwt:
    validity-time: 30